package com.evolutionary.credit.domain;

/** 信用域错误码。 */
public enum CreditErrorCode {
    CREDIT_LIMIT_EXCEEDED,
    CREDIT_OVERDUE_BLOCKED,
    CREDIT_PROFILE_FROZEN,
    CREDIT_NOT_AVAILABLE,
    PRODUCT_NOT_ELIGIBLE,
    PRODUCT_NOT_PUBLISHED,
    STATEMENT_NOT_DUE,
    PARTIAL_REPAY_NOT_ALLOWED,
    INSUFFICIENT_BALANCE,
    POLICY_LIMIT_EXCEEDED
}
