package com.evolutionary.commerce.domain;

public enum DomainErrorCode {
    INSUFFICIENT_BALANCE,
    PRODUCT_NOT_PUBLISHED,
    ENTITLEMENT_INACTIVE,
    ENTITLEMENT_EXPIRED,
    ENTITLEMENT_EXHAUSTED,
    BATTERY_NOT_AVAILABLE,
    BATTERY_ALREADY_RENTED,
    REFUND_BLOCKED_IN_PROGRESS_SWAP,
    ORDER_NOT_REFUNDABLE
}
